package main

var cssMap map[string]string = map[string]string{
	"#header":     `height:100px;`,
	"#body":       "height:560px;top:100px;font-size:12px;",
	"#footer":     `height:130px;top:660px;font-size:12px;`,
	"tr":          `flex-direction: row;`,
	"#htitle":     `margin:0px;font-size:26px;text-align:center;display:flex;flex-direction:row;`,
	"#htitle>div": `flex:1;line-height:44px;font-weight: bold;color:#ff0000;`,
	".dline":      `border-top:0.5px solid #f00;border-bottom:0.5px solid #f00;padding-top:1px;margin:5px 0px`,
	".sline":      `border-top:0.5px solid #333;margin:5px 0px`,
	".title":      "font-weight:bold;font-size:13px;margin-top:10px;margin-bottom: 5px;",
	".line":       "padding-left:14px;",
	"#info":       "line-height: 20px;padding:0 14px;",
	"#info>tr":    "border-bottom: 0.5px dotted #000000;",
	"#plist>td":   `border: 0.5px solid #f00;padding:2px`,
	"#plist>tr":   "margin:0 14px;",
	"#receipt":    "line-height: 20px;padding:0 14px;",
	"#receipt>td": `border: 0.5px solid #ccc;padding:2px`,
	".td1":        "flex:1",
	".td2":        "flex:1",
	".td3":        "flex:2",
	".td4":        "flex:3",
	".td5":        "flex:2",
	".td6":        "flex:3",
	".td7":        "flex:2",
	".c1":         "flex:3",
	".c2":         "flex:6",
	".c3":         "flex:14",
	".c4":         "flex:3;text-align:center",
	".c5":         "flex:10",
}
